### ISSUE TITLE
수정요청

### ISSUE THREAD

**Issue by crongro** [pdvonzoo/codesquad#1]
```javascript
  answer[0] = Math.floor(Math.random() * 10);
  answer[1] = Math.floor(Math.random() * 10);
  answer[2] = Math.floor(Math.random() * 10);
```

올려주신 코드에 이런 코드가 두 군데 정도 보입니다.
저 코드를, answer 배열을 반환하는 getRandomValue 함수를 새롭게 만들어서 처리하도록 해보세요

```javascript
answer = getRandomValue();
```

**Comment by pdvonzoo** [comment]
안녕하세요. 정말 반갑습니다.
코멘트 해주신 부분 감사합니다.

먼저 말씀해주신대로 두 부분으로 나뉘어져 있던 answer 관련 코드를 하나의 함수에서만 나타나게 작성해보았습니다.
확인 부탁드리겠습니다.
감사합니다.

**Comment by crongro** [comment]
네 확인했어요.
잘 하셨네요 :-)
